### ISSUE TITLE
Add quiltflower / make default source decompiler

### ISSUE THREAD

**Issue by tennox** [architectury/architectury-templates#10]
I think it's widely agreed that quiltflower's sources are nicer to read.
Adding them seems to be quite simple with [LoomQuiltflower plugin](https://github.com/Juuxel/LoomQuiltflower).

Maybe it could even be the default one when running `genSources` ?

**Comment by triphora** [comment]
I know that upstream loom was considering this at one point, but I don't think we're going to diverge from what upstream does in this regard.

**Comment by tennox** [comment]
I see. you mean fabric-loom?
Okay that might be a political thing then. 😅

**Comment by MaxNeedsSnacks** [comment]
Less so about politics, more about practicality, since it'd generally be a good idea to follow KISS when it comes to templates imo. Nonetheless, I've brought it up on Discord, and even if we end up deciding against it, it's a one-line change to apply LQF like you said

**Comment by tennox** [comment]
Ah I agree with the staying with upstream part, that's not what I meant. I thought forge-loom is the upstream you mean?

And yes it's a simple change just thought to improve the dev experience of the template. As I had only stumbled upon that by accident and just thought - hm, why isn't this the default.

But in any case, thanks for following up on it 👍

**Comment by MaxNeedsSnacks** [comment]
Forge Loom *is* Architectury Loom, the original project was made by Juuz and he's continuing his work here :p

**Comment by tennox** [comment]
TIL... 😲
Thanks for the insights :)
