### ISSUE TITLE
Intellij runs not compileing befor run

### ISSUE THREAD

**Issue by rubenh2905** [architectury/architectury-templates#16]
After i imported project in to idea with runing following commands

```
.\gradlew.bat configureClientLaunch
.\gradlew.bat idea
.\gradlew.bat openIdea
```

i tryed to launch game with idea runs but it's not compiling code until i run

```
.\gradlew.bat runClient
```
manually

this is my gradle.properties
```
# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# tell architectury loom that this project is a forge project.
# this will enable us to use the "forge" dependency.
# using archloom without this is possible and will give you a
# "standard" loom installation with some extra features.
loom.platform=forge

# Base properties
    # minecraft version
    minecraft_version=1.19.3
    # forge version, latest version can be found on https://files.minecraftforge.net/
    forge_version=1.19.3-44.1.0
    # yarn, latest version can be found on https://fabricmc.net/develop/
    yarn_mappings=1.19.3+build.5

# Mod Properties
    mod_version=1.0.0
    maven_group=com.example.examplemod
    archives_base_name=archloom-example-mod
    mod_id=archloom-example-mod
    mod_author=TheExampleDev
```

**Comment by Juuxel** [comment]
```
.\gradlew.bat configureClientLaunch
.\gradlew.bat idea
.\gradlew.bat openIdea
```

You should not use these commands, instead just import the Gradle project in IDEA.

> i tryed to launch game with idea runs but it's not compiling code

What do you exactly mean by this? Does the game launch at all, or is there some error message? Make sure that you have set "Build and run: Gradle" in the IDEA settings screen's Gradle section.

**Comment by rubenh2905** [comment]
if you try to run it with .\gradlew.bat runClient it will run without problem , but i dont know how to pass arguments to program with this gradle command , but if you try to run with intellij generated command it does run launcher but dont compile project or at last build folder will not generate and it will crash because it cant find build folder

**Comment by Juuxel** [comment]
Make sure that the run configuration in IDEA has the "Do not build before run" option unticked as shown here:
![kuva](https://user-images.githubusercontent.com/6596629/225748587-5f04cce7-447c-4b86-b18d-5a0afd7d49ae.png)

You can find this menu by clicking "Modify options" in the run configuration window.
