### ISSUE TITLE
Change 'mixins' to 'mixin' in quilt.mod.json and add examplemod.mixins.json to mixins module

### ISSUE THREAD

**Issue by Trikzon** [architectury/architectury-templates#6]
The quilt.mod.json generated by these templates currently produces
```
{
...
  "mixins": [
    "examplemod.mixins.json",
    "examplemod-common.mixins.json"
  ],
...
}
```
however, quilt requires it to be `mixin` instead of `mixins`.

So instead, these templates should generate
```
{
...
  "mixin": [
    "examplemod.mixins.json",
    "examplemod-common.mixins.json"
  ],
...
}
```

Also, `examplemod.mixins.json` isn't generated by the templates either in the quilt module, so that should also be fixed.

**Comment by shedaniel** [comment]
Thanks!
